### ISSUE TITLE
Plugin does not get correct data only on android

### ISSUE THREAD

**Issue by Bradrickcruz** [lynrin/cordova-plugin-buildinfo#24]
## **Environment**
Linux Mint 21.1 Cinnamon
Linux Kernel 5.15.0-84-generic

cordova 11.1.0
cordova-android 11.0.0
cordova-ios 6.2
node 16.19.0

Java JDK: 11.0.20
Gradle: 8.1.1
Android target: android-33,android-32,android-31,android-30,android-29

## **Problem**
After i update my app to use cordova 11.1 (before it was 10), cordova-android 11 (before it was 9) to target android 33 (before it was 30), when i tried to get the data of BuildInfo on javascript, the plugin return all data as null, empty strings or zero value. This happens only when i build the app with ```cordova build --release android --buildConfig ```, because when i use ```cordova build --debug android --buildConfig``` it works fine. The only difference of these commands is "--debug" generate an ".apk" and "--release" generates an ".aab".

I suppose that some of the updates change something that broke the plugin.

**Comment by lynrin** [comment]
Hello @Bradrickcruz

Did you specify ``minifyEnabled true`` during release build?

As far as I tried, I was able to get data even with release builds.
However, I encountered a problem when I set ``minifyEnabled true`` and did a release build.

Since this plugin obtains information from the BuildConfig class, please try adding the following to the proguard settings.

````
-keep public class **.BuildConfig { *; }
````

**Comment by Bradrickcruz** [comment]
it works, thank you.

**Comment by lynrin** [comment]
I'm glad it worked.
